Fixed build with installed package

diff --git a/src/jsc b/src/jsc
--- a/src/jsc
+++ b/src/jsc
@@ -11,15 +11,15 @@ mkdir -p ${TMP_PATH}
 touch ${LOG_PATH}
 
 echo -e "> Generating AST json"
-${SCRIPT_PATH}/../build/generate_json_ast $1 ${TMP_PATH}/ast.json &> ${LOG_PATH}
+${SCRIPT_PATH}/jscompiler/generate_json_ast $1 ${TMP_PATH}/ast.json &> ${LOG_PATH}
 
 echo -e "> Generating AST c++ constexpr representation"
 command -v json2cpp &> /dev/null || { echo >&2 "json2cpp is required. Aborting."; exit 1; }
-json2cpp prog ${TMP_PATH}/ast.json ${TMP_PATH}/ast &> ${LOG_PATH}
+${SCRIPT_PATH}/jscompiler/json2cpp prog ${TMP_PATH}/ast.json ${TMP_PATH}/ast &> ${LOG_PATH}
 
 echo -e "> Compiling AST to exe"
 command -v cmake &> /dev/null || { echo >&2 "cmake is required. Aborting."; exit 1; }
 echo -e "  > Configuring with cmake"
-cmake ${SCRIPT_PATH} -B ${TMP_PATH} -DCMAKE_BUILD_TYPE=RelWithDebInfo &> ${LOG_PATH} || { echo >&2 "cmake configure step failed. Aborting."; exit 1; }
+cmake ${SCRIPT_PATH}/../etc/jscompiler -B ${TMP_PATH} -DCMAKE_BUILD_TYPE=RelWithDebInfo &> ${LOG_PATH} || { echo >&2 "cmake configure step failed. Aborting."; exit 1; }
 echo -e "  > Building with cmake"
 cmake --build ${TMP_PATH} &> ${LOG_PATH} || { echo >&2 "cmake build step failed. Aborting."; exit 1; }
